
#######################
#### http server   ####
#######################
server:
  session.timeout: 3600000
  ip: localhost
  port: 10002

#######################
#### LOG           ####
#######################
logging:
  config: classpath:log4j2-dev.yml
  level:
    com.youzidata: DEBUG




